### PR TITLE
Rework CI and fix an error

### PR DESCRIPTION
**Pull request by HeMan**
Add compilation test and fix #5

### CODE REVIEW

**Comment by PLXT** [comment]
it finally works🍺

**Comment by HeMan** [comment]
Solves https://github.com/esphome/issues/issues/5258

**Review by thijstriemstra — APPROVED** [review]

**Comment by maciekish** [comment]
Hi, please update platformio repository with this fix. Also having the `#if LWIP_IPV4 && LWIP_IPV6` issue.

**Comment by thijstriemstra** [comment]
Please merge, this also fixed issue for me.

cc @jesserockz

**Comment by DaviVolcan** [comment]
still waiting the merge...

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
